# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  Thanks for opening this pull request! :)

  I am simply testing this bot :)

# Comment to be posted to on new issues
newIssueWelcomeComment: >
  Hello there!👋 Welcome to the project!💖

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Admittedly, github is confusing sometimes :)
