name: Auto Comment
on: [issues, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1.1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            👋 
            Thanks for opening this issue! We will investigate into the matter and get back to you as soon as possible. Please make sure you have given us as much context as possible:
            
            - Includes any code snippets, and/or any CLI outcomes that come with your issue (If possible, copy the error text directly rather than screenshotting) and also what code you were running when you encountered this issue, all within ``` blocks ``` using “```”
            - Includes the version number of each of the following: Pushkin, Pushkin-cli, experiment and site template, node.js.
            - Links to any relevant issues.
            - If your issue is about JsPsych and not about the integration/interaction between JsPsych and Pushkin, then post the issue to JsPsych’s [GitHub page](https://github.com/jspsych/jsPsych/issues).
            - Stay patient! While waiting for a response, head on over to [our discussions page](https://github.com/pushkin-consortium/pushkin/discussions)!

            For more information on coding-related questions: 
            
            - [JavaScript Tutorial](https://www.codecademy.com/learn/introduction-to-javascript)
            - [JsPsych Tutorial](https://www.jspsych.org/7.3/tutorials/hello-world/#jspsych-hello-world-experiment)
            - [Pushkin Docs](https://languagelearninglab.gitbook.io/pushkin/)

          pullRequestOpened: |
            👋 
            Thanks for making this pull request! We will review it as soon as possible, in the meantime, double check that your PR:

            
            - Includes a thorough explanation of what your pull request is changing/adding to Pushkin.
            - Links to any relevant issues to the pull request.
            - In the interest of good development habits, if you wish to commit changes, create a new branch and then submit a pull request with your changes.
