name: Auto Comment
on: [issues, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1.1.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            👋 
            Thanks for opening this issue! We will investigate into the matter and get back to you as soon as possible. Please make sure you have given us as much context as possible:
            
            - Remember to include any code snippets, CLI outcomes, and/or screenshots/GIFs that come with your issue.
            - Remember to link relevant issues to yours whenever possible.
            - Remember to stay patient! While waiting for a response, head on over to our discussions page if there hasn’t been a response.
            - [JavaScript Tutorial](https://www.codecademy.com/learn/introduction-to-javascript)

          pullRequestOpened: |
            👋 
            Thanks for making this pull request! We will review it as soon as possible
            
            - Remember to include any code snippets, CLI outcomes, and/or screenshots/GIFs that come with your issue.
            - Remember to link relevant issues to yours whenever possible.
            - Out of good pull request habit, remember to fork the main repo, and create your own branches before committing any changes to the code, where you can then choose to create a pull request back to the main branch


